# Auto-generated by scripts/sync-gnome-settings.sh
# Do not edit manually — re-run the script to update.
{ lib, pkgs, ... }:
let
  focusTerminal = pkgs.writeShellScriptBin "gnome-focus-terminal" ''
    # Try to focus existing Alacritty window via GNOME extension D-Bus
    result=$(gdbus call --session \
      --dest org.gnome.Shell \
      --object-path /de/lucaswerkmeister/ActivateWindowByTitle \
      --method de.lucaswerkmeister.ActivateWindowByTitle.ActivateByWmClass "Alacritty" 2>/dev/null)

    if [[ "$result" != *"true"* ]]; then
      /home/orre/.nix-profile/bin/alacritty -e /home/orre/.nix-profile/bin/zellij attach --create main &
    fi
  '';
in
{
  home.packages = [
    pkgs.gnomeExtensions.activate-window-by-title
    pkgs.gnomeExtensions.tiling-shell
  ];
  dconf.settings = {
    "org/gnome/shell" = {
      enabled-extensions = [
        "activate-window-by-title@lucaswerkmeister.de"
        "tilingshell@ferrarodomenico.com"
      ];
    };

    "org/gnome/desktop/interface" = {
      color-scheme = "prefer-dark";
      show-battery-percentage = true;
      toolkit-accessibility = false;
    };

    "org/gnome/desktop/input-sources" = {
      # sources = [('xkb', 'fi')]  # TODO: manual conversion needed
      xkb-options = [ "terminate:ctrl_alt_bksp" ];
    };

    "org/gnome/desktop/wm/keybindings" = {
      close = [ "<Shift><Super>q" ];
      switch-to-workspace-1 = [ "<Super>1" ];
      switch-to-workspace-2 = [ "<Super>2" ];
      switch-to-workspace-3 = [ "<Super>3" ];
      switch-to-workspace-4 = [ "<Super>4" ];
      switch-to-workspace-5 = [ "<Super>5" ];
      switch-to-workspace-6 = [ "<Super>6" ];
      switch-to-workspace-7 = [ "<Super>7" ];
      switch-to-workspace-8 = [ "<Super>8" ];
      switch-to-workspace-9 = [ "<Super>9" ];
    };

    "org/gnome/desktop/wm/preferences" = {
      num-workspaces = 9;
    };

    "org/gnome/desktop/break-reminders/eyesight" = {
      play-sound = true;
    };

    "org/gnome/desktop/break-reminders/movement" = {
      duration-seconds = 300;
      interval-seconds = 1800;
      play-sound = true;
    };

    "org/gnome/mutter" = {
      dynamic-workspaces = true;
      experimental-features = [];
      overlay-key = "";
      workspaces-only-on-primary = true;
    };

    "org/gnome/mutter/keybindings" = {
      toggle-tiled-left = [ "<Super>Left" ];
      toggle-tiled-right = [ "<Super>Right" ];
    };

    "org/gnome/shell/keybindings" = {
      show-screenshot-ui = [ "<Super>p" ];
      switch-to-application-1 = [];
      switch-to-application-2 = [];
      switch-to-application-3 = [];
      switch-to-application-4 = [];
      switch-to-application-5 = [];
      switch-to-application-6 = [];
      switch-to-application-7 = [];
      switch-to-application-8 = [];
      switch-to-application-9 = [];
      toggle-overview = [ "<Super>d" ];
    };

    "org/gnome/shell/app-switcher" = {
      current-workspace-only = false;
    };

    "org/gnome/settings-daemon/plugins/color" = {
      night-light-enabled = false;
      night-light-schedule-automatic = false;
    };

    "org/gnome/settings-daemon/plugins/media-keys" = {
      custom-keybindings = [ "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/" "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/" ];
    };

    "org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0" = {
      binding = "<Super>Return";
      command = "${focusTerminal}/bin/gnome-focus-terminal";
      name = "Focus Terminal";
    };

    "org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1" = {
      binding = "<Ctrl><Super>Return";
      command = "/home/orre/.nix-profile/bin/alacritty -e /home/orre/.nix-profile/bin/zellij";
      name = "New Terminal";
    };

    "org/gnome/nautilus/preferences" = {
      default-folder-viewer = "list-view";
      migrated-gtk-settings = true;
    };

    "org/gtk/gtk4/settings/file-chooser" = {
      show-hidden = true;
      sort-directories-first = false;
    };

    "org/gtk/settings/file-chooser" = {
      date-format = "regular";
      location-mode = "path-bar";
      show-hidden = true;
      show-size-column = true;
      show-type-column = true;
      sort-column = "modified";
      sort-directories-first = false;
      sort-order = "descending";
      type-format = "category";
    };

  };
}
