#!/usr/bin/env bash
# Sync current GNOME dconf settings to Home Manager repo
set -euo pipefail

REPO_DIR="${HOME}/.config/home-manager"
OUTPUT="${REPO_DIR}/modules/desktop/gnome-dconf-dump.nix"
RAW_DUMP="${REPO_DIR}/modules/desktop/gnome-dconf.dump"

# Save raw dump for reference
dconf dump / > "$RAW_DUMP"

# Paths worth tracking (intentional settings, not transient state)
INCLUDE_PATHS=(
  /org/gnome/desktop/interface/
  /org/gnome/desktop/input-sources/
  /org/gnome/desktop/wm/keybindings/
  /org/gnome/desktop/wm/preferences/
  /org/gnome/desktop/break-reminders/eyesight/
  /org/gnome/desktop/break-reminders/movement/
  /org/gnome/mutter/
  /org/gnome/mutter/keybindings/
  /org/gnome/shell/
  /org/gnome/shell/keybindings/
  /org/gnome/shell/app-switcher/
  /org/gnome/settings-daemon/plugins/color/
  /org/gnome/settings-daemon/plugins/media-keys/
  /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/
  /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/
  /org/gnome/nautilus/preferences/
  /org/gtk/gtk4/settings/file-chooser/
  /org/gtk/settings/file-chooser/
)

# Generate Nix dconf.settings (data only — no packages or scripts)
cat > "$OUTPUT" << 'HEADER'
# Auto-generated by scripts/sync-gnome-settings.sh
# Do not edit manually — re-run the script to update.
# This file is imported by modules/desktop/gnome.nix
{ lib, ... }:
{
  dconf.settings = {
HEADER

for path in "${INCLUDE_PATHS[@]}"; do
  section="${path#/}"          # strip leading /
  section="${section%/}"       # strip trailing /
  nix_key="${section}"

  # Read all keys in this path
  keys=$(dconf list "$path" 2>/dev/null | grep -v '/$' || true)
  [ -z "$keys" ] && continue

  echo "    \"${nix_key}\" = {" >> "$OUTPUT"

  for key in $keys; do
    value=$(dconf read "${path}${key}" 2>/dev/null || true)
    [ -z "$value" ] && continue

    # Skip transient values (timestamps, window sizes, positions)
    case "$key" in
      *timestamp*|*window-size*|*window-state*|*window-position*|*height|*width|*initial-size*) continue ;;
    esac

    # Convert GVariant to Nix
    nix_value=""
    case "$value" in
      # Boolean
      true|false)
        nix_value="$value"
        ;;
      # String
      \'*\')
        inner="${value#\'}"
        inner="${inner%\'}"
        nix_value="\"${inner}\""
        ;;
      # uint32
      uint32\ *)
        nix_value="${value#uint32 }"
        ;;
      # int64
      int64\ *)
        continue  # skip timestamps
        ;;
      # Array of strings ['a', 'b']
      \[\'*)
        nix_value="[ "
        # Parse comma-separated quoted strings
        cleaned="${value#[}"
        cleaned="${cleaned%]}"
        IFS=',' read -ra items <<< "$cleaned"
        for item in "${items[@]}"; do
          item="${item## }"    # trim leading space
          item="${item#\'}"    # strip leading quote
          item="${item%\'}"    # strip trailing quote
          nix_value+="\"${item}\" "
        done
        nix_value+="]"
        ;;
      # Tuple like ('xkb', 'fi')
      \(*)
        echo "      # ${key} = ${value}  # TODO: manual conversion needed" >> "$OUTPUT"
        continue
        ;;
      # Array with tuples [('xkb', 'fi')]
      \[\(*)
        echo "      # ${key} = ${value}  # TODO: manual conversion needed" >> "$OUTPUT"
        continue
        ;;
      # Empty array @as []
      @as\ \[\])
        nix_value="[]"
        ;;
      # Other typed empty arrays
      @*\ \[\])
        nix_value="[]"
        ;;
      # Plain integers
      [0-9]*)
        nix_value="$value"
        ;;
      *)
        echo "      # ${key} = ${value}  # TODO: unsupported type" >> "$OUTPUT"
        continue
        ;;
    esac

    echo "      ${key} = ${nix_value};" >> "$OUTPUT"
  done

  echo "    };" >> "$OUTPUT"
  echo "" >> "$OUTPUT"
done

cat >> "$OUTPUT" << 'FOOTER'
  };
}
FOOTER

echo "✓ Generated: ${OUTPUT}"
echo "✓ Raw dump:  ${RAW_DUMP}"
echo ""
echo "Review changes with: git diff modules/desktop/gnome-dconf-dump.nix"
